### ISSUE TITLE
Profiler doesn't start

### ISSUE THREAD

**Issue by moskalenko** [what-studio/profiling#27]
```python
Traceback (most recent call last):
  File "/apps/python/2.7.6/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/apps/python/2.7.6/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/apps/python/2.7.6/lib/python2.7/site-packages/profiling/__main__.py", line 592, in <module>
    cli(prog_name='python -m profiling')
  File "/apps/python/2.7.6/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/apps/python/2.7.6/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/apps/python/2.7.6/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/apps/python/2.7.6/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/apps/python/2.7.6/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/apps/python/2.7.6/lib/python2.7/site-packages/profiling/__main__.py", line 347, in profile
    dump_filename=dump_filename, mono=mono)
  File "/apps/python/2.7.6/lib/python2.7/site-packages/profiling/__main__.py", line 314, in __profile__
    loop.run()
  File "/apps/python/2.7.6/lib/python2.7/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/apps/python/2.7.6/lib/python2.7/site-packages/urwid/main_loop.py", line 375, in _run
    self.event_loop.run()
  File "/apps/python/2.7.6/lib/python2.7/site-packages/urwid/main_loop.py", line 678, in run
    self._loop()
  File "/apps/python/2.7.6/lib/python2.7/site-packages/urwid/main_loop.py", line 699, in _loop
    ready, w, err = select.select(fds, [], fds, timeout)
select.error: (9, 'Bad file descriptor')
```

**Comment by sublee** [comment]
How can I reproduce this error?

**Comment by sublee** [comment]
Is it still active issue?

**Comment by sublee** [comment]
@moskalenko If you let me know that this issue is sill active, I'll reopen it.
