### ISSUE TITLE
Recursion RuntimeError on importing Requests lib

### ISSUE THREAD

**Issue by lockwooddev** [what-studio/profiling#32]
I'm running into a weird issue while trying to profile a simple project. I isolated the problem to the [Requests](https://github.com/kennethreitz/requests) library.

Just by importing requests (I tested 2.6.2 and 2.7.0), profiling will throw a recursion runtime error.

I'm using OSX 10.10.5 and python 3.4. Can anyone replicate this behaviour?

Here is the isolated script:

```python
import requests

print('Hello World')
```

This is the console output after it does nothing for a while:
(NOTE: It does execute the Hello World print)

```bash
(testenv)Mac:active-monitoring-plugin carlo$ python -m profiling profile ~/Desktop/weird.py
Hello World
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/__main__.py", line 674, in <module>
    cli(prog_name='python -m profiling')
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/__main__.py", line 399, in wrapped
    return f(**kwargs)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/__main__.py", line 376, in wrapped
    return f(profiler_factory=profiler_factory, **kwargs)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/__main__.py", line 488, in profile
    mono=mono)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/__main__.py", line 447, in __profile__
    stats, cpu_time, wall_time = profiler.result()
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/tracing/__init__.py", line 123, in result
    frozen_stats, cpu_time, wall_time = base.result()
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/profiler.py", line 63, in result
    frozen_stats = FrozenStatistics(self.stats)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 50, in __call__
    obj = super(StatisticsMeta, cls).__call__(*args, **kwargs)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 257, in __init__
    self._children = self._freeze_children(stats)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 262, in _freeze_children
    return [cls(s) for s in children]
...
...
...
    return [cls(s) for s in children]
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 262, in <listcomp>
    return [cls(s) for s in children]
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 50, in __call__
    obj = super(StatisticsMeta, cls).__call__(*args, **kwargs)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 257, in __init__
    self._children = self._freeze_children(stats)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 262, in _freeze_children
    return [cls(s) for s in children]
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 262, in <listcomp>
    return [cls(s) for s in children]
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 50, in __call__
    obj = super(StatisticsMeta, cls).__call__(*args, **kwargs)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 252, in __init__
    value = getattr(stats, attr)
  File "/Users/carlo/.virtualenvs/testenv/lib/python3.4/site-packages/profiling/stats.py", line 186, in module
    module = inspect.getmodule(self.code)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py", line 612, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py", line 595, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py", line 583, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py", line 612, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/inspect.py", line 596, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/Users/carlo/.virtualenvs/testenv/bin/../lib/python3.4/posixpath.py", line 357, in abspath
    if not isabs(path):
  File "/Users/carlo/.virtualenvs/testenv/bin/../lib/python3.4/posixpath.py", line 62, in isabs
    sep = _get_sep(s)
RuntimeError: maximum recursion depth exceeded
```

**Comment by sublee** [comment]
Thanks to report the bug.  It was caused by recursive function calls to freeze profiling result.  I fixed this issue at b0fb2d to avoid the recursion by another approach.  Can you review it?

**Comment by lockwooddev** [comment]
No more recursion exceptions, thanks for the quick fix!

**Comment by sublee** [comment]
I'll merge this.  Thanks to review.
