### ISSUE TITLE
Profiling django's dev server

### ISSUE THREAD

**Issue by Ernest0x** [what-studio/profiling#34]
Hello,

I tried to profile django's dev server with `profiling live-profile manage.py runserver`, but without success. The viewer seems that is showing only calls for bootstrapping django. Nothing happens as requests are made to the server. Am I missing something? Or is what I am trying to do currently not supported?

**Comment by sublee** [comment]
Would you try again with Sampling Profiler by `-S` option?  If Profiling still fails, please let me reproduce this issue by some example project.

**Comment by otrenav** [comment]
I can confirm that `$ profling live-profile -S manage.py runserver` is not working. Neither `$ profiling live-profile -S manage.py -- runserver`. In both cases I get a "- Not Available-" message, and when `Ctrl-C`, I can see an `Exception Error: 'NoneType' object is not callable` because the process can not import the project settings file.

Probably has to do with the scope under it's being executed.

**Comment by Ernest0x** [comment]
> Would you try again with Sampling Profiler by -S option? If Profiling still fails, please let me reproduce this issue by some example project.

Running `profiling live-profile -S manage.py runserver` no calls are shown in the viewer (is shows '- Not Available - ') and if I hit the enter key I get the following traceback:

```
Traceback (most recent call last):
  File "/path/to/python/virtual/environment/bin/profiling", line 9, in <module>
    load_entry_point('profiling==0.0.0.dev0', 'console_scripts', 'profiling')()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/__main__.py", line 523, in wrapped
    return f(**kwargs)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/__main__.py", line 500, in wrapped
    return f(profiler_factory=profiler_factory, **kwargs)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/__main__.py", line 634, in live_profile
    loop.run()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/main_loop.py", line 719, in _loop
    self._watch_files[fd]()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/viewer.py", line 717, in keypress
    self.viewer.pause()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/viewer.py", line 827, in pause
    self._paused_result = self._final_result
AttributeError: 'StatisticsViewer' object has no attribute '_final_result'
```

Perhaps the traceback above is just some unhandled case when not having results to show, but I am reporting it nevertheless.

**Comment by Ernest0x** [comment]
Reproducing this is fairly easy: Just start a new project (with `django-admin startproject exampleproject`) and run `profiling live-profile [-S] manage.py runserver`. It is likely that you get a traceback with an error like "ImportError: No module named 'exampleproject'". I am not sure with this is happening when running manage.py through profiling, but you can workaround it by adding the following 2 lines in the manage.py script:
```Python
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
sys.path.append(BASE_DIR)
```

**Comment by sublee** [comment]
The `AttributeError` is fixed at 34a61b02855986a8c6acf82cf914607f298453bf.  Thanks to report it.

Now I'm trying to reproduce the Django issue.

**Comment by sublee** [comment]
I fixed the `ImportError` at df2fc23d5afbad33b78e829a31971b8145539106.

But I got an "Interrupted system call" error when a viewer activates.  I guess that Django's auto-reload behavior is incompatible with our Profiling server.  If you don't use the auto-reloader, Profiling seems to work well:

```console
$ profiling live manage.py runserver -- --noreload
```

`--` before `--noreload` is necessary.  It separates `--noreload` from the Profiling's argument parser.

**Comment by Ernest0x** [comment]
With `profiling live manage.py runserver -- --noreload`, I got some activity related to django's built-in server, but there were no calls related to the actual requests made to the server. I had to pass the option '--nothreading' to django's runserver command to get profiling stats for calls related to requests. Are multithreaded applications not supported?

Sampling profiler with `profiling live -S manage.py runserver -- --noreload` still does not work, but this time exiting the profiling gives a max recursion traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/remote/__init__.py", line 230, in connected
    self._start_profiling()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/remote/select.py", line 44, in _start_profiling
    self.profile_periodically()
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/remote/select.py", line 47, in profile_periodically
    for __ in self.profiling():
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/remote/__init__.py", line 185, in profiling
    pickle_protocol=self.pickle_protocol)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/remote/__init__.py", line 62, in pack_msg
    pickle.dump(msg, dump, pickle_protocol)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 250, in __reduce__
    return FrozenStatistics.reduce_stats(self)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 147, in reduce_stats
    members = [getattr(stats, attr) for attr in cls.__slots__]
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 147, in <listcomp>
    members = [getattr(stats, attr) for attr in cls.__slots__]
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <genexpr>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
  File "/path/to/python/virtual/environment/lib/python3.4/site-packages/profiling/stats.py", line 260, in <lambda>
    deep_time = property(lambda x: sum(s.deep_time for s in x), _ignore)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by sublee** [comment]
Profiling should support multithreading.

To debug the problem, I need to make a Django application calculating a factorial number.  But I don't know about Django at all.  Can you teach me how can I make it?

```
GET /{n} -> factorial of n
```

By the way, I'll re-implement `deep_time` without recursion to fix the `RuntimeError` soon.

**Comment by Ernest0x** [comment]
> To debug the problem, I need to make a Django application calculating a factorial number. But I don't know about Django at all. Can you teach me how can I make it?

Sure.

You may create a django project  with `django-admin startproject factorial`. Then, in the inner 'factorial' directory (where urls.py, settings.py, etc. exist) create a 'views.py' file that looks like this:
```Python
from django.http import HttpResponse
import math

def factorial(request, n):
    n = int(n)
    return HttpResponse(math.factorial(n))
```

Last, make the 'urls.py' file look like this:
```Python
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<n>[0-9]+)', views.factorial),
]
```

**Comment by sublee** [comment]
I fixed the recursion error at f8f0bc7844fc694361b88f9606d5a5cd6fd2e6ee. Would you try to profile again?

**Comment by sublee** [comment]
Originally, `ProfilingServer` excluded its threading code to avoid some of profiling pollution.  But it excluded Django's threading code also.

I should consider the excluding behavior again.  Currently, I just made `ProfilingServer` to not exclude anything at 75afa81b680928da77683ac024acbc9e8dadcd3e.  Now `profiling live` shows the business logic in my Django application without `--nothreading` option.

**Comment by sublee** [comment]
@Ernest0x Please give me some feedback?

**Comment by Ernest0x** [comment]
`profiling live -S manage.py runserver -- --noreload` (sampling profiler) still gives maximum recursion runtime error but with a differenct traceback this time:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/remote/__init__.py", line 222, in connected
    self._start_profiling()
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/remote/select.py", line 44, in _start_profiling
    self.profile_periodically()
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/remote/select.py", line 47, in profile_periodically
    for __ in self.profiling():
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/remote/__init__.py", line 177, in profiling
    pickle_protocol=self.pickle_protocol)
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/remote/__init__.py", line 60, in pack_msg
    pickle.dump(msg, dump, pickle_protocol)
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/stats.py", line 284, in __reduce__
    return FrozenStatistics.reduce_stats(self)
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/stats.py", line 181, in reduce_stats
    members = [getattr(stats, attr) for attr in cls.__slots__]
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/stats.py", line 181, in <listcomp>
    members = [getattr(stats, attr) for attr in cls.__slots__]
  File "/path/to/python/virtual/env/lib/python3.4/site-packages/profiling/stats.py", line 239, in module
    module = inspect.getmodule(self.code)
  File "/usr/lib/python3.4/inspect.py", line 612, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.4/inspect.py", line 595, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/lib/python3.4/inspect.py", line 583, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.4/inspect.py", line 612, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.4/inspect.py", line 596, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.4/posixpath.py", line 357, in abspath
    if not isabs(path):
  File "/usr/lib/python3.4/posixpath.py", line 62, in isabs
    sep = _get_sep(s)
RuntimeError: maximum recursion depth exceeded
```

`profiling live manage.py runserver -- --noreload` now works without passing `--nothreading`, but it is very slow. A request that takes ~1 sec, will take 1.2 mins when run through the profiler.

**Comment by sublee** [comment]
I'm going to fix the new recursion error.

The performance loss was probably caused by using `TracingProfiler` instead of `SamplingProfiler`.  Try again with `-S` option.

**Comment by sublee** [comment]
@Ernest0x I re-implemented Pickle integration without any recursive call.  Perhaps your recursion issue has been fixed.  See 47de3919532f1ce8073fa0d9b590b7c9f070ce0f.

**Comment by Ernest0x** [comment]
> @Ernest0x I re-implemented Pickle integration without any recursive call. Perhaps your recursion issue has been fixed. See 47de391.

Yes, the recursion issue has been fixed and the sampling profiler now works. Thanks. It is also very quick. So quick that live profiling of fast server responses is almost impossible as they disappear very quickly from the viewer :). Perhaps it would be a nice feature to make the viewer's output persistent.

**Comment by sublee** [comment]
@Ernest0x You can use `-i` option to adjust update interval.  It's default value is 1 second which can be too fast for some applications.

```console
$ profiling live -i 5 manage.py runserver -- --noreload
```
