### ISSUE TITLE
windows live-profiling exception

### ISSUE THREAD

**Issue by hofst** [what-studio/profiling#9]
getting an exception directly at starting:

Traceback (most recent call last):
  File "C:\Program Files\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Program Files\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Program Files\Python27\lib\site-packages\profiling\__main__.py", line 33, in <module>
    from .remote.background import START_SIGNO, STOP_SIGNO, BackgroundProfiler
  File "C:\Program Files\Python27\lib\site-packages\profiling\remote\background.py", line 20, in <module>
    START_SIGNO = signal.SIGUSR1
AttributeError: 'module' object has no attribute 'SIGUSR1'

**Comment by sublee** [comment]
It looks impossible until `urwid` which is the TUI library supports Windows.  Sorry for the bad news.
